/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowDownIcon: typeof import('./components/common/icons/ArrowDownIcon.vue')['default']
    ArrowUpIcon: typeof import('./components/common/icons/ArrowUpIcon.vue')['default']
    BadgeComponent: typeof import('./components/common/BadgeComponent.vue')['default']
    CheckboxComponent: typeof import('./components/common/CheckboxComponent.vue')['default']
    CheckIcon: typeof import('./components/common/icons/CheckIcon.vue')['default']
    CloseIcon: typeof import('./components/common/icons/CloseIcon.vue')['default']
    DeleteIcon: typeof import('./components/common/icons/DeleteIcon.vue')['default']
    ExtraData: typeof import('./components/lists/ExtraData.vue')['default']
    FooterPage: typeof import('./components/footer/FooterPage.vue')['default']
    HeaderPage: typeof import('./components/header/HeaderPage.vue')['default']
    IconComponent: typeof import('./components/common/IconComponent.vue')['default']
    LinkIcon: typeof import('./components/common/icons/LinkIcon.vue')['default']
    ListData: typeof import('./components/lists/ListData.vue')['default']
    ListItems: typeof import('./components/lists/ListItems.vue')['default']
    ListUnit: typeof import('./components/lists/ListUnit.vue')['default']
    ListUnits: typeof import('./components/lists/ListUnits.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    MenuParent: typeof import('./components/menu/MenuParent.vue')['default']
    MinusIcon: typeof import('./components/common/icons/MinusIcon.vue')['default']
    ParachuteIcon: typeof import('./components/common/icons/ParachuteIcon.vue')['default']
    PlusIcon: typeof import('./components/common/icons/PlusIcon.vue')['default']
    PrintIcon: typeof import('./components/common/icons/PrintIcon.vue')['default']
    RadioGroup: typeof import('./components/common/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveIcon: typeof import('./components/common/icons/SaveIcon.vue')['default']
    SheetOptions: typeof import('./components/lists/SheetOptions.vue')['default']
    ToastListComponent: typeof import('./components/toast/ToastListComponent.vue')['default']
    UndoIcon: typeof import('./components/common/icons/UndoIcon.vue')['default']
    UnitInput: typeof import('./components/lists/UnitInput.vue')['default']
    UnitTable: typeof import('./components/lists/UnitTable.vue')['default']
  }
}
